package by.bsuir.pogen.forms;

import by.bsuir.pogen.constants.Constants;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.watertemplate.Template;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

/**
 * Created by alexei.khilchuk on 09/04/2017.
 */
public class ClassEditorForm extends JFrame {
    public JPanel mainPanel;
    private JEditorPane epCode;
    private JButton btnSave;

    public ClassEditorForm(Template classTemplate, final Constants.ProgrammingLanguage language) {
        super("Generated Page Object Class");
        epCode.setText(classTemplate.render());
        btnSave.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                saveAs(language);
            }
        });
    }

    public void saveAs(Constants.ProgrammingLanguage language) {
        FileNameExtensionFilter extensionFilter = null;
        switch (language) {
            case JAVA: {
                extensionFilter = new FileNameExtensionFilter("Java Class File", "java");
                break;
            }
            case C_SHARP: {
                extensionFilter = new FileNameExtensionFilter("C# Class File", "cs");
                break;
            }
        }

        final JFileChooser saveAsFileChooser = new JFileChooser();
        saveAsFileChooser.setApproveButtonText("Save");
        saveAsFileChooser.setFileFilter(extensionFilter);
        int actionDialog = saveAsFileChooser.showOpenDialog(this);
        if (actionDialog != JFileChooser.APPROVE_OPTION) {
            return;
        }

        File file = saveAsFileChooser.getSelectedFile();
        if (!file.getName().endsWith("." + extensionFilter.getExtensions()[0])) {
            file = new File(file.getAbsolutePath() + "." + extensionFilter.getExtensions()[0]);
        }

        BufferedWriter outFile = null;
        try {
            outFile = new BufferedWriter(new FileWriter(file));

            epCode.write(outFile);

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } finally {
            if (outFile != null) {
                try {
                    outFile.close();
                } catch (IOException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
            }
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        epCode = new JEditorPane();
        epCode.setFont(new Font("Courier New", epCode.getFont().getStyle(), 16));
        mainPanel.add(epCode, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(800, 600), new Dimension(800, 600), null, 0, false));
        btnSave = new JButton();
        btnSave.setFont(new Font("Segoe UI Semibold", btnSave.getFont().getStyle(), 18));
        btnSave.setText("Save Class");
        mainPanel.add(btnSave, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
