package by.bsuir.pogen.forms;

import by.bsuir.pogen.models.WebElement;
import by.bsuir.pogen.models.WebElementNode;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.openqa.selenium.remote.RemoteWebDriver;

import javax.swing.*;
import javax.swing.tree.DefaultTreeModel;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 * Created by Alexei Khilchuk on 13.02.2017.
 */
public class GeneratorForm extends JFrame {
    public JPanel mainPanel;
    private JTree trWebElements;
    private RemoteWebDriver webDriver;

    public GeneratorForm(RemoteWebDriver currentWebDriver) {
        super("Generator");
        webDriver = currentWebDriver;
        webDriver.manage().window().setPosition(new org.openqa.selenium.Point(-2000, 0));
        Document doc = Jsoup.parse(webDriver.getPageSource());
        WebElementNode htmlTree = new WebElementNode(new WebElement(doc.body()));


        DefaultTreeModel treeModel = new DefaultTreeModel(htmlTree);
        this.trWebElements.setModel(treeModel);


        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                if (webDriver != null) {
                    webDriver.close();
                    webDriver.quit();
                }
            }
        });

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        trWebElements = new JTree();
        mainPanel.add(trWebElements, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final JLabel label1 = new JLabel();
        label1.setText("Elements:");
        mainPanel.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
